### ISSUE TITLE
STHM Sync not working

### ISSUE THREAD

**Issue by ThomasTrain** [rtorchia/DSC-Envisalink#6]
Issue:  With latest commit on 10/25, STHM monitor to DSC Panel sync is not working.

Replication:  

1) Disable all automations related to STHM/DSC panel sync.
2) Attempt to arm STHM - DSC panel does not arm.

3) check alarmserver log contains following entries:

2020-10-29 11:05:56 RX < 502 - 023 - System Error 023
2020-10-29 11:05:56 TX > 0401367499

2020-10-29 11:05:56 RX < 502 - 023 - System Error 023

**Comment by rtorchia** [comment]
fixed so Stay and Away panels will respond to STHM triggers
